version: '2.2'
services:
    app:  
        build: .
        image: sibtaskssti
        ports:
          - "9980:80"
        volumes:
          - ./flag.txt:/app/flag.txt:ro
        mem_limit: 1G
        memswap_limit: 1G
        cpu_count: 1
        pids_limit: 256
        ulimits: 
            nofile:
                soft: 8192
                hard: 8192
        restart: always

